### ISSUE TITLE
Disconnect with book content and exercise file layout

### ISSUE THREAD

**Issue by LoPan455** [TrainingByPackt/Beginning-Springboot#1]
The exercise file layout in the book's screenshots for lesson 2 look very different from the code in this repository.  The package names are different between the book and repo.  This makes it very difficult to follow along with the content of the book.

**Comment by pcornelissen** [comment]
That shouldn't be the case, can you elaborate where it differs?

**Comment by pcornelissen** [comment]
You didn't provide any pointers, so I'll close this one. Feel free to reopen it when you can provide more information.
